kit:
  name: "Component Vertica"
  link: https://github.com/qubell-bazaar/component-vertica
https://github.com/qubell-bazaar/component-mysql-dev 
  applications:
    - name: "Vertica"
      manifest: https://raw.github.com/qubell-bazaar/component-vertica/master/component-vertica.yml
https://raw.github.com/qubell-bazaar/component-mysql-dev/master/component-mysql-dev.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
        * Ports 5450 and Vertica specific open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
